name: CI-CD pipeline para sitios de juegos

on: 
    push:
        branches: [ main ]

jobs: 
    build-and-test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          
          - name: Instalar Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20'

          - name: validar  HTML
            run: npx htmlhint index.html
              
          - name: Busqueda de links rotos 
            uses: justinBeckwith/linkinator-action@v1
            with:
              paths: 'index.html'

    deplay:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Deploy GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                publish-dir: ./
                